In [179]:
import os
import csv
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

Current working directory C:\Users\SFLORES\Documents\T\NN Python
Directory changed successfully C:\Users\SFLORES\Documents\T\NN Python


In [ ]:
!wget https://raw.githubusercontent.com/sam517/NN-Cheng/master/datos/abalone_train_5.2

In [180]:
data=[]
with open("abalone_train_5.2") as tsv:
    
    reader=csv.reader(tsv,delimiter=' ', quoting=csv.QUOTE_NONNUMERIC)
    for row in reader:
        data.append(row)

my_array=np.array(data,dtype=np.float64);
my_array.shape
X=my_array[:,1:11]
X.shape
y=my_array[:,0]
y=y.astype(np.uint8)
print (y.dtype, y.shape)

uint8 (1000,)


In [181]:
#Normalize X

for j in range(X.shape[1]):
    print(j)
    base=min(X[:,j])
    spread=max(X[:,j])-base
    z=X[:,j]
    z=2*(z-base)/spread - 1
    X[:,j]=z

0
1
2
3
4
5
6
7
8
9


In [182]:
#Start counting in 0 for the categories of y
#Here we create a matrix Y that holds 0 and 1's according to 
#the paper for ordinal regression

n=y.shape[0]
nclasses=max(y)-min(y)+1

Y=np.zeros((n,nclasses))

for i in range(n):
    #print(i)
    c=y[i]+1
    for j in range(c):
        #print(j)
        Y[i,j]=1


In [183]:
#Placeholders
X_=tf.placeholder(tf.float32, shape=X.shape)
Y_=tf.placeholder(tf.float32, shape=Y.shape)


In [184]:
#Model definition

#Hidden units
HU=8

#First layer
W1=tf.Variable(tf.random_uniform([X.shape[1],HU],-1.0,1.0)) #Weights matrix
b1=tf.Variable(tf.zeros([HU])) #Bias
O=tf.nn.tanh(tf.matmul(X_,W1)+b1) #Output from the first layer

#Second layer
W2=tf.Variable(tf.random_uniform([HU,nclasses],-1.0,1.0))
b2=tf.Variable(tf.zeros([nclasses]))
YHat=tf.nn.sigmoid(tf.matmul(O,W2)+b2)


In [188]:
#Loss and optimizer definition
#Cross entropy loss function

cost=tf.reduce_sum(tf.nn.sigmoid_cross_entropy_with_logits(labels=Y_,logits=YHat))
#Hace lo mismo que la fn de arriba cost=tf.reduce_sum(Y_*-tf.log(tf.sigmoid(YHat))+(1-Y_)*-tf.log(1-tf.sigmoid(YHat)),reduction_indices=[0,1])
#Optimizing the function cost by gradient descent with learning step 0.01
train_step=tf.train.GradientDescentOptimizer(0.01).minimize(cost)

In [189]:
#Create the session and initialize variables
sess=tf.Session()

sess.run(tf.global_variables_initializer())


In [190]:
#Training 

Epochs=2000

error=np.zeros((Epochs))

for e in range(Epochs):
    sess.run(train_step, feed_dict={X_:X,Y_:Y})	#Optimizer step
    print("Epoch=",e)
    error[e]=sess.run(cost,feed_dict={X_:X,Y_:Y})
    print("Cost=",error[e])

Epoch= 0
Cost= 2958.72119140625
Epoch= 1
Cost= 2834.66845703125
Epoch= 2
Cost= 2828.6103515625
Epoch= 3
Cost= 2825.24560546875
Epoch= 4
Cost= 2822.984375
Epoch= 5
Cost= 2821.316162109375
Epoch= 6
Cost= 2819.994140625
Epoch= 7
Cost= 2818.8857421875
Epoch= 8
Cost= 2817.89453125
Epoch= 9
Cost= 2816.946533203125
Epoch= 10
Cost= 2815.97265625
Epoch= 11
Cost= 2814.8779296875
Epoch= 12
Cost= 2813.53662109375
Epoch= 13
Cost= 2811.7548828125
Epoch= 14
Cost= 2809.2822265625
Epoch= 15
Cost= 2806.024169921875
Epoch= 16
Cost= 2802.5078125
Epoch= 17
Cost= 2799.4326171875
Epoch= 18
Cost= 2796.92041015625
Epoch= 19
Cost= 2794.84521484375
Epoch= 20
Cost= 2793.0732421875
Epoch= 21
Cost= 2791.53369140625
Epoch= 22
Cost= 2790.179931640625
Epoch= 23
Cost= 2788.978515625
Epoch= 24
Cost= 2787.909912109375
Epoch= 25
Cost= 2786.960693359375
Epoch= 26
Cost= 2786.11865234375
Epoch= 27
Cost= 2785.37646484375
Epoch= 28
Cost= 2784.72509765625
Epoch= 29
Cost= 2784.171142578125
Epoch= 30
Cost= 2783.7421875
Epoch= 31


Epoch= 261
Cost= 2774.1826171875
Epoch= 262
Cost= 2774.1796875
Epoch= 263
Cost= 2774.176513671875
Epoch= 264
Cost= 2774.173095703125
Epoch= 265
Cost= 2774.169921875
Epoch= 266
Cost= 2774.16650390625
Epoch= 267
Cost= 2774.162841796875
Epoch= 268
Cost= 2774.159423828125
Epoch= 269
Cost= 2774.156005859375
Epoch= 270
Cost= 2774.15283203125
Epoch= 271
Cost= 2774.14990234375
Epoch= 272
Cost= 2774.146728515625
Epoch= 273
Cost= 2774.14404296875
Epoch= 274
Cost= 2774.140869140625
Epoch= 275
Cost= 2774.137939453125
Epoch= 276
Cost= 2774.134765625
Epoch= 277
Cost= 2774.1318359375
Epoch= 278
Cost= 2774.128662109375
Epoch= 279
Cost= 2774.12548828125
Epoch= 280
Cost= 2774.122314453125
Epoch= 281
Cost= 2774.11962890625
Epoch= 282
Cost= 2774.11669921875
Epoch= 283
Cost= 2774.113525390625
Epoch= 284
Cost= 2774.11083984375
Epoch= 285
Cost= 2774.108154296875
Epoch= 286
Cost= 2774.10546875
Epoch= 287
Cost= 2774.1025390625
Epoch= 288
Cost= 2774.099853515625
Epoch= 289
Cost= 2774.096923828125
Epoch= 290
Cos

Cost= 2773.69775390625
Epoch= 532
Cost= 2773.696533203125
Epoch= 533
Cost= 2773.6953125
Epoch= 534
Cost= 2773.694580078125
Epoch= 535
Cost= 2773.693359375
Epoch= 536
Cost= 2773.6923828125
Epoch= 537
Cost= 2773.69140625
Epoch= 538
Cost= 2773.6904296875
Epoch= 539
Cost= 2773.68896484375
Epoch= 540
Cost= 2773.688232421875
Epoch= 541
Cost= 2773.68701171875
Epoch= 542
Cost= 2773.68603515625
Epoch= 543
Cost= 2773.68505859375
Epoch= 544
Cost= 2773.683837890625
Epoch= 545
Cost= 2773.682861328125
Epoch= 546
Cost= 2773.681640625
Epoch= 547
Cost= 2773.6806640625
Epoch= 548
Cost= 2773.6796875
Epoch= 549
Cost= 2773.6787109375
Epoch= 550
Cost= 2773.677734375
Epoch= 551
Cost= 2773.6767578125
Epoch= 552
Cost= 2773.676025390625
Epoch= 553
Cost= 2773.6748046875
Epoch= 554
Cost= 2773.673828125
Epoch= 555
Cost= 2773.67236328125
Epoch= 556
Cost= 2773.671630859375
Epoch= 557
Cost= 2773.67041015625
Epoch= 558
Cost= 2773.66943359375
Epoch= 559
Cost= 2773.6689453125
Epoch= 560
Cost= 2773.667724609375
Epoch= 56

Epoch= 810
Cost= 2773.470947265625
Epoch= 811
Cost= 2773.470703125
Epoch= 812
Cost= 2773.4697265625
Epoch= 813
Cost= 2773.46923828125
Epoch= 814
Cost= 2773.46826171875
Epoch= 815
Cost= 2773.4677734375
Epoch= 816
Cost= 2773.467041015625
Epoch= 817
Cost= 2773.46630859375
Epoch= 818
Cost= 2773.465576171875
Epoch= 819
Cost= 2773.46484375
Epoch= 820
Cost= 2773.46435546875
Epoch= 821
Cost= 2773.46337890625
Epoch= 822
Cost= 2773.462890625
Epoch= 823
Cost= 2773.462158203125
Epoch= 824
Cost= 2773.4619140625
Epoch= 825
Cost= 2773.4609375
Epoch= 826
Cost= 2773.46044921875
Epoch= 827
Cost= 2773.459716796875
Epoch= 828
Cost= 2773.458984375
Epoch= 829
Cost= 2773.45849609375
Epoch= 830
Cost= 2773.4580078125
Epoch= 831
Cost= 2773.457275390625
Epoch= 832
Cost= 2773.45654296875
Epoch= 833
Cost= 2773.455810546875
Epoch= 834
Cost= 2773.455078125
Epoch= 835
Cost= 2773.45458984375
Epoch= 836
Cost= 2773.453857421875
Epoch= 837
Cost= 2773.453125
Epoch= 838
Cost= 2773.45263671875
Epoch= 839
Cost= 2773.45190429

Cost= 2773.30615234375
Epoch= 1090
Cost= 2773.305908203125
Epoch= 1091
Cost= 2773.305419921875
Epoch= 1092
Cost= 2773.304931640625
Epoch= 1093
Cost= 2773.30419921875
Epoch= 1094
Cost= 2773.303955078125
Epoch= 1095
Cost= 2773.30322265625
Epoch= 1096
Cost= 2773.302734375
Epoch= 1097
Cost= 2773.30224609375
Epoch= 1098
Cost= 2773.301513671875
Epoch= 1099
Cost= 2773.301025390625
Epoch= 1100
Cost= 2773.300537109375
Epoch= 1101
Cost= 2773.300048828125
Epoch= 1102
Cost= 2773.29931640625
Epoch= 1103
Cost= 2773.298828125
Epoch= 1104
Cost= 2773.29833984375
Epoch= 1105
Cost= 2773.2978515625
Epoch= 1106
Cost= 2773.29736328125
Epoch= 1107
Cost= 2773.296875
Epoch= 1108
Cost= 2773.296142578125
Epoch= 1109
Cost= 2773.29541015625
Epoch= 1110
Cost= 2773.294921875
Epoch= 1111
Cost= 2773.29443359375
Epoch= 1112
Cost= 2773.2939453125
Epoch= 1113
Cost= 2773.29345703125
Epoch= 1114
Cost= 2773.29296875
Epoch= 1115
Cost= 2773.29248046875
Epoch= 1116
Cost= 2773.291748046875
Epoch= 1117
Cost= 2773.291259765625
Ep

Cost= 2773.1611328125
Epoch= 1369
Cost= 2773.16064453125
Epoch= 1370
Cost= 2773.16015625
Epoch= 1371
Cost= 2773.15966796875
Epoch= 1372
Cost= 2773.1591796875
Epoch= 1373
Cost= 2773.15869140625
Epoch= 1374
Cost= 2773.157958984375
Epoch= 1375
Cost= 2773.157470703125
Epoch= 1376
Cost= 2773.156982421875
Epoch= 1377
Cost= 2773.156494140625
Epoch= 1378
Cost= 2773.15625
Epoch= 1379
Cost= 2773.15576171875
Epoch= 1380
Cost= 2773.155029296875
Epoch= 1381
Cost= 2773.15478515625
Epoch= 1382
Cost= 2773.154296875
Epoch= 1383
Cost= 2773.153564453125
Epoch= 1384
Cost= 2773.153076171875
Epoch= 1385
Cost= 2773.152587890625
Epoch= 1386
Cost= 2773.15234375
Epoch= 1387
Cost= 2773.1513671875
Epoch= 1388
Cost= 2773.151123046875
Epoch= 1389
Cost= 2773.150390625
Epoch= 1390
Cost= 2773.150146484375
Epoch= 1391
Cost= 2773.149658203125
Epoch= 1392
Cost= 2773.149169921875
Epoch= 1393
Cost= 2773.1484375
Epoch= 1394
Cost= 2773.14794921875
Epoch= 1395
Cost= 2773.1474609375
Epoch= 1396
Cost= 2773.14697265625
Epoch= 13

Cost= 2773.03857421875
Epoch= 1641
Cost= 2773.038330078125
Epoch= 1642
Cost= 2773.03759765625
Epoch= 1643
Cost= 2773.03759765625
Epoch= 1644
Cost= 2773.03662109375
Epoch= 1645
Cost= 2773.036376953125
Epoch= 1646
Cost= 2773.0361328125
Epoch= 1647
Cost= 2773.035888671875
Epoch= 1648
Cost= 2773.03564453125
Epoch= 1649
Cost= 2773.03515625
Epoch= 1650
Cost= 2773.034912109375
Epoch= 1651
Cost= 2773.0341796875
Epoch= 1652
Cost= 2773.033935546875
Epoch= 1653
Cost= 2773.03369140625
Epoch= 1654
Cost= 2773.033203125
Epoch= 1655
Cost= 2773.03271484375
Epoch= 1656
Cost= 2773.03271484375
Epoch= 1657
Cost= 2773.032470703125
Epoch= 1658
Cost= 2773.031982421875
Epoch= 1659
Cost= 2773.03173828125
Epoch= 1660
Cost= 2773.03125
Epoch= 1661
Cost= 2773.03125
Epoch= 1662
Cost= 2773.03076171875
Epoch= 1663
Cost= 2773.03076171875
Epoch= 1664
Cost= 2773.03076171875
Epoch= 1665
Cost= 2773.0302734375
Epoch= 1666
Cost= 2773.030517578125
Epoch= 1667
Cost= 2773.030517578125
Epoch= 1668
Cost= 2773.03076171875
Epoch= 1

Cost= 2773.03515625
Epoch= 1920
Cost= 2773.081298828125
Epoch= 1921
Cost= 2773.03466796875
Epoch= 1922
Cost= 2773.0810546875
Epoch= 1923
Cost= 2773.0341796875
Epoch= 1924
Cost= 2773.080810546875
Epoch= 1925
Cost= 2773.033935546875
Epoch= 1926
Cost= 2773.08056640625
Epoch= 1927
Cost= 2773.033203125
Epoch= 1928
Cost= 2773.080078125
Epoch= 1929
Cost= 2773.03271484375
Epoch= 1930
Cost= 2773.080078125
Epoch= 1931
Cost= 2773.03271484375
Epoch= 1932
Cost= 2773.07958984375
Epoch= 1933
Cost= 2773.0322265625
Epoch= 1934
Cost= 2773.07958984375
Epoch= 1935
Cost= 2773.0322265625
Epoch= 1936
Cost= 2773.0791015625
Epoch= 1937
Cost= 2773.03173828125
Epoch= 1938
Cost= 2773.078857421875
Epoch= 1939
Cost= 2773.03125
Epoch= 1940
Cost= 2773.07861328125
Epoch= 1941
Cost= 2773.03076171875
Epoch= 1942
Cost= 2773.078369140625
Epoch= 1943
Cost= 2773.0302734375
Epoch= 1944
Cost= 2773.077880859375
Epoch= 1945
Cost= 2773.0302734375
Epoch= 1946
Cost= 2773.077880859375
Epoch= 1947
Cost= 2773.02978515625
Epoch= 1948


In [191]:
predictions=sess.run(YHat,feed_dict={X_:X,Y_:Y})

predictions=np.round(predictions,1)

print ("Output:", predictions)

Output: [[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]


In [192]:
Y_Prediction=np.zeros(n)

for i in range(n):
    for j in range(predictions.shape[1]):
        
        if predictions[i,j] > 0.5:
            Y_Prediction[i]=Y_Prediction[i]+1
        else:
            break

In [193]:
yc=y+1
correct_prediction=abs(yc-Y_Prediction)<0.5
cast=tf.cast(correct_prediction,"float")
accuracy=tf.reduce_mean(cast)
acc=sess.run(accuracy)
print ("Accuracy",acc)

Accuracy 0.782


In [ ]:
np.savetxt("Y_Prediction.csv", [Y_Prediction,yc], delimiter=",")